project: 
  type: website

website:
  title: "The Economics Experience"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Microeconomics"
        href: microeconomics/index.qmd
      - text: "Macroeconomics"
        href: macroeconomics/index.qmd
      - text: "Downloads"
        href: downloads/index.qmd
      - text: "About"
        href: about.qmd
     
  sidebar:
   
    - id: microeconomics
      title: "Microeconomics"
      style: "docked"
      search: true
      background: "secondary"
      collapse-level: 1
      contents: 
        - text: "Home"
          href: index.qmd
        - auto: "microeconomics/"
      
    - id: macroeconomics
      title: "Macroeconomics"
      style: "docked"
      search: true
      background: "secondary"
      collapse-level: 1
      contents: 
        - text: "Home"
          href: index.qmd
        - auto: "macroeconomics/"
      
    - id: downloads
      title: "Downloads"
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - text: "Home"
          href: index.qmd
        - auto: "downloads/"
      
    - id: home
      title: "Navigation"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Home"
          href: index.qmd
        - text: "Microeconomics"
          href: microeconomics/index.qmd
        - text: "Macroeconomics"
          href: macroeconomics/index.qmd
        - text: "Downloads"
          href: downloads/index.qmd
        - text: "About"
          href: about.qmd
      
  page-navigation: false
  back-to-top-navigation: true
  
  page-footer:
    background: dark
    left: "Copyright 2025, Meghan Downes"
    right: 
      - icon: github
        href: https://github.com/meghandownes
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - Make Sure to Check Here for Announcements!"
    type: warning
    position: below-navbar
  
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    
 

