project: 
  type: website

website:
  title: "The Economics Experience"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Microeconomics"
        href: microeconomics.qmd
      - text: "Macroeconomics"
        href: macroeconomics.qmd
      - text: "Downloads"
        href: downloads.qmd
  
  sidebar:
    style: "docked"
    search: true
    contents: auto
    background: light
    site-path: "https://rubyrooster.com"
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    background: dark
    left: "Copyright 2025, Meghan Downes"
    right: 
      - icon: github
        href: https://github.com/meghandownes
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this is some information that you should pay attention to"
    type: primary
    position: below-navbar
  open-graph: true
  twitter-card: true
  favicon: nofreelunch.png

format:
  html:
    theme: lux
    css: styles.css
    toc: true
 

