project: 
  type: website

website:
  title: "The Economics Experience"
  navbar:
    background: primary
    search: true
    collapse: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Microeconomics"
        href: microeconomics
      - text: "Macroeconomics"
        href: macroeconomics
  sidebar:
    style: "docked"
    search: true
    background: "secondary"
    foreground: "info"
    contents: auto
    
 
  page-navigation: true
  back-to-top-navigation: true
  
  page-footer:
    background: dark
    left: "Copyright 2025, Meghan Downes"
    right: 
      - icon: github
        href: https://github.com/meghandownes
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this is some information that you should pay attention to"
    type: primary
    position: below-navbar
  
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    
 

