---
title: "Lab 2: Opportunity Cost"
author: "Meghan Downes"
format:
  html: 
    toc: true
    css: styles.css
---

For this lab, you are going to create a page about opportunity cost. Please complete the following components:

1.  Create a folder labeled, "macroeconomics-learning-journal"
2.  Create a note titled, "opportunity-cost"
3.  Add the following H1 headings (a single #):
    1.  Definition
    2.  Example (text)
    3.  Formula
    4.  Graph
    5.  Real-Life Example -- from *your* life -- not from the internet, but your own lived experience
    6.  **AI Output** -- You do NOT have to use AI. There are ethical and moral issues, and the use of AI is NOT required. This is for IF you use AI, develop a habit of including it in your notes or workflow.
4.  Add links using the double square brackets:
    1.  Opportunity Cost
    2.  Trade-Offs
5.  Find material from your textbook that is relevant and helps provide details and grounding in accuracy. Paste it into your file.
6.  Write a prompt for your favorite AI about opportunity cost. Paste the contents, including the prompt (export) into the section labeled AI.
7.  Reflect on the differences between the lecture, textbook, and AI:
    1.  What are the differences?
    2.  What is your key takeaway about Opportunity Cost?
8.  Please upload your markdown file to the assignment drop box in Canvas.
    1.  name your file, "lastname-firstname-opportunity-cost"
